---
title: "January_challenge"
author: "Arindam Baruah"
format: html
---

```{r, message=FALSE,echo=FALSE}
# Load libraries
library(galah)
library(tidyverse)
library(ggplot2)
library(nullabor)
library(leaflet)
library(spatstat) 
library(plotly)
library(tsibble)
library(sf)
library(rmapshaper)
library(lubridate)
library(broom)
library(GGally)
library(forecast)
library(ggalt)
library(rnoaa)
library(UpSetR)
library(stringr)
library(caret)
library(DT)
library(mltools)
library(data.table)
```



```{r}


# Dataset
input <- c(
  M.acuminata = 759,
  P.dactylifera = 769,
  A.thaliana = 1187,
  O.sativa = 1246,
  S.bicolor = 827,
  B.distachyon = 387,
  "P.dactylifera&M.acuminata" = 467,
  "O.sativa&M.acuminata" = 29,
  "A.thaliana&O.sativa" = 6,
  "S.bicolor&A.thaliana" = 9,
  "O.sativa&P.dactylifera" = 32,
  "S.bicolor&P.dactylifera" = 49,
  "S.bicolor&M.acuminata" = 49,
  "B.distachyon&O.sativa" = 547,
  "S.bicolor&O.sativa" = 1151,
  "B.distachyon&A.thaliana" = 10,
  "B.distachyon&M.acuminata" = 9,
  "B.distachyon&S.bicolor" = 402,
  "M.acuminata&A.thaliana" = 155,
  "A.thaliana&P.dactylifera" = 105,
  "B.distachyon&P.dactylifera" = 25,
  "S.bicolor&O.sativa&P.dactylifera" = 42,
  "B.distachyon&O.sativa&P.dactylifera" = 12,
  "S.bicolor&O.sativa&B.distachyon" = 2809,
  "B.distachyon&O.sativa&A.thaliana" = 18,
  "S.bicolor&O.sativa&A.thaliana" = 40,
  "S.bicolor&B.distachyon&A.thaliana" = 14,
  "O.sativa&B.distachyon&M.acuminata" = 28,
  "S.bicolor&B.distachyon&M.acuminata" = 13,
  "O.sativa&M.acuminata&P.dactylifera" = 35,
  "M.acuminata&S.bicolor&A.thaliana" = 21,
  "B.distachyon&M.acuminata&A.thaliana" = 7,
  "O.sativa&M.acuminata&A.thaliana" = 13,
  "M.acuminata&P.dactylifera&A.thaliana" = 206,
  "P.dactylifera&A.thaliana&S.bicolor" = 4,
  "O.sativa&A.thaliana&P.dactylifera" = 6,
  "S.bicolor&O.sativa&M.acuminata" = 64,
  "S.bicolor&M.acuminata&P.dactylifera" = 19,
  "B.distachyon&A.thaliana&P.dactylifera" = 3,
  "B.distachyon&M.acuminata&P.dactylifera" = 12,
  "B.distachyon&S.bicolor&P.dactylifera" = 23,
  "M.acuminata&B.distachyon&S.bicolor&A.thaliana" = 54,
  "P.dactylifera&S.bicolor&O.sativa&M.acuminata" = 62,
  "B.distachyon&O.sativa&M.acuminata&P.dactylifera" = 18,
  "S.bicolor&B.distachyon&O.sativa&A.thaliana" = 206,
  "B.distachyon&M.acuminata&O.sativa&A.thaliana" = 29,
  "O.sativa&M.acuminata&A.thaliana&S.bicolor" = 71,
  "M.acuminata&O.sativa&P.dactylifera&A.thaliana" = 28,
  "B.distachyon&M.acuminata&O.sativa&A.thaliana" = 7,
  "B.distachyon&S.bicolor&P.dactylifera&A.thaliana" = 11,
  "B.distachyon&O.sativa&P.dactylifera&A.thaliana" = 5,
  "A.thaliana&P.dactylifera&S.bicolor&O.sativa" = 21,
  "M.acuminata&S.bicolor&P.dactylifera&A.thaliana" = 23,
  "M.acuminata&B.distachyon&S.bicolor&P.dactylifera" = 24,
  "M.acuminata&O.sativa&S.bicolor&B.distachyon" = 368,
  "P.dactylifera&B.distachyon&S.bicolor&O.sativa" = 190,
  "P.dactylifera&B.distachyon&S.bicolor&O.sativa&A.thaliana" = 258,
  "P.dactylifera&M.acuminata&S.bicolor&B.distachyon&O.sativa" = 685,
  "M.acuminata&S.bicolor&B.distachyon&O.sativa&A.thaliana" = 1458,
  "S.bicolor&M.acuminata&P.dactylifera&O.sativa&A.thaliana" = 149,
  "B.distachyon&M.acuminata&P.dactylifera&O.sativa&A.thaliana" = 80,
  "M.acuminata&S.bicolor&B.distachyon&P.dactylifera&A.thaliana" = 113,
  "M.acuminata&S.bicolor&B.distachyon&P.dactylifera&O.sativa&A.thaliana" = 7674
)

```



```{r}
# Plot
upset(fromExpression(input), 
      nintersects = 40, 
      nsets = 6, 
      order.by = "freq", 
      decreasing = T, 
      mb.ratio = c(0.6, 0.4),
      number.angles = 0, 
      text.scale = 1.1, 
      point.size = 2.8, 
      line.size = 1
      )
```

```{r}
df <- read_csv("data/goodreads_top100.csv")

```

```{r}
df$Genres <- str_replace_all(df$Genres,"[\\[\\]]","")



split_data <- str_split(df$Genres, ",")

# Convert the result to a matrix
result_matrix <- do.call(rbind, split_data)

# Convert the matrix to a data frame
result_df <- as.data.frame(result_matrix)

# Set column names
colnames(result_df) <- paste0("V", seq_len(ncol(result_df)))

# Print the resulting data frame
print(result_df)


```



```{r}



DF <- as.data.frame(unclass(result_df),stringsAsFactors=TRUE)
df <- cbind(df,DF)

df <- df %>% select(-c(Genres,Description,Series,`Release number`,Author,`Num Pages`,`Publication Date`,Rating,...1))
```

```{r}

col_name <- c("Book","V1","V2","V3","V4","V5","V6","V7")
categorical_columns <- c("V1","V2","V3","V4","V5","V6","V7")
df_compact <- df %>% select(all_of(col_name))

df_long <- df_compact %>% pivot_longer(cols = c("V1","V2","V3","V4","V5","V6","V7"),values_to = "Genre")

dummy_variables <- lapply(categorical_columns, function(column) {
  levels <- unique(df_compact[[column]])
  dummy_matrix <- sapply(levels, function(level) as.integer(df_compact[[column]] == level))
  colnames(dummy_matrix) <- paste0(column, "_", levels)
  return(dummy_matrix)
})


encoded_data <- cbind(df_compact,dummy_variables)

# Print the result
print(encoded_data)

```







```{r}
encoded_data <- encoded_data %>% select(-categorical_columns)
names(encoded_data) = gsub(pattern = "V1_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "V2_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "V3_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "V4_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "V5_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "V6_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "V7_*", replacement = "", x = names(encoded_data))
names(encoded_data) = gsub(pattern = "'*", replacement = "", x = names(encoded_data))
names(encoded_data) = trimws(names(encoded_data))
```




```{r}
text_scale_options1 <- c(1, 1, 1, 1, 0.75, 1)
text_scale_options2 <- c(1.3, 1.3, 1, 1, 2, 0.75)
text_scale_options3 <- c(1.5, 1.25, 1.25, 1, 2, 1.5)


main_bar_col <- c("violetred4")
sets_bar_col <- c("turquoise4")
matrix_col <- c("slateblue4")
shade_col <- c("wheat4")

#I called it "1" because I anticipated others
#but never needed them
mb_ratio1 <- c(0.55,0.45)

set_vars <- c("Fiction","Historical Fiction","Sports")

upset(encoded_data, 
	sets = set_vars,
	mainbar.y.label = "Counts by Pattern of Conditions", 
	sets.x.label = "Counts by Condition",
	order.by = "freq",
	show.numbers = FALSE,
	point.size = 2, 
	line.size = 1,
	text.scale=text_scale_options3,
	main.bar.color = main_bar_col,
	sets.bar.color = sets_bar_col,
	matrix.color = matrix_col,
	shade.color = shade_col)
```




```{r}
df_long$Genre <- str_replace(df_long$Genre,"'","")
df_long$Genre <- str_replace(df_long$Genre,"'","")
df_long$Genre <- str_replace(df_long$Genre," ","")
#df_long <- df_long %>% select(-name)


genre_matrix <- table(df_long$Book, df_long$Genre) > 0

df_matrix <- as.data.frame(genre_matrix)
set_vars <- unique(colnames(df_matrix))

df_matrix <- df_matrix %>% rownames_to_column(var = "Book")



df_matrix <- df_matrix %>% 
  mutate(across(everything(), ~+as.logical(.x)))

df_matrix <- df_matrix %>% select(-Book)

set_vars <- unique(colnames(df_matrix))
upset(df_matrix,
      	sets = set_vars)
```







