---
title: "Exercise 3"
author: "Arindam Baruah"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
```


```{r}
df <- read_csv("data.csv",skip = 1)

df_clean <- df %>% select(2:dim(df)[2]) %>% rename("Type" = "...2")
```

```{r}
df_long <- df_clean %>% pivot_longer(names_to = "Year",
                                     values_to = "Percentage",cols = 2:5) %>% filter(Type != "Total")
```


```{r}
pl1 <-
  ggplot(data = df_long, aes(x = Year, y = round(Percentage,0), group = Type)) +
  geom_line(color = "gray",size = 3) + theme_economist() +  geom_text(
    aes(label = round(Percentage,0)),
    vjust = -1,
    size = 7,
    color = "gray"
  ) + labs(x = "Year",
           y = "Percentage automation trend (%)",
           title = "Surging Automation: Home Equity Line \n of Credit Moves Up to Second Place Among Payment Methods") + theme(
             legend.text = element_text(size = 6),
             axis.text = element_text(size = 14,
                                      face = "bold"),
             axis.title = element_text(size = 15,face = "bold"),
             plot.title = element_text(size = 25, hjust = 0.5),
             panel.background = element_rect(fill = 'cornsilk')
           ) + geom_line(
                                                            data = ~ filter(.x, Type == "Home Equity Line of Credit"),
                                                            color = "darkgreen",
                                                            size = 5,
                                                    
                                                          )  + geom_label(
                                                            data = filter(df_long, Year == 2023),
                                                            aes(label = Type),
                                                            vjust = -0.05,
                                                            hjust = -0.15,
                                                            size = 4,
                                                            color = "black"
                                                          ) + geom_point(color = "black", size = 7) + geom_text(data = ~filter(.x,Type == "Home Equity Line of Credit"),
                                                                                                                aes(label = round(Percentage,0)),
                                                                                                                color = "black",size = 7,vjust = -1,
    size = 7,)

# Hide legend for color
pl1 + guides(color = guide_legend(override.aes = list(label = c(""))))
```

```{r}

```

